[package]
name = "c2pa-wasm"
version = "0.1.0"
authors = ["Eli Mensch <mensch@adobe.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.100"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }
console_log = { version = "1.0.0", features = ["color"] }
log = "0.4.27"
js-sys = "0.3.77"
wasm-bindgen-futures = "0.4.50"
c2pa = { version = "0.58.0", features = ["pdf", "rust_native_crypto"], default-features = false }
async-trait = "0.1.88"
thiserror = "2.0.12"

[dependencies.web-sys]
version = "0.3.77"
features = [
	'console',
	'Blob',
	'FileReaderSync',
]

[dev-dependencies]
wasm-bindgen-test = "0.3.50"
