name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: ./.github/actions/install-dependencies
        name: Install dependencies

      # Install chrome + chromedriver for vitest + wasm-pack test
      - run: pnpx playwright install --with-deps

      - run: pnpm exec nx run-many -t lint test build --projects=tag:lib
