name: Build and publish docs

on:
  push:
    branches: ['main']
    tags: '*'

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - uses: ./.github/actions/install-dependencies
        name: Install dependencies

      - run: pnpm exec nx run-many -t build --projects=tag:lib

      - name: Build docs
        run: pnpm ci:docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
